name: CI

on:
  workflow_dispatch:
    inputs:
      PackageVersion:
        description: 'The version of the package to push to NuGet'
        required: true
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src/SSR.Net/SSR.Net.csproj'
      BUILD_VERSION: "${{ github.event.inputs.PackageVersion }}" 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet pack $SOLUTION --configuration $BUILD_CONFIG /p:Version=$BUILD_VERSION

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
